#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/ulagellam-logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Ulagellam"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "© 2016-2022 Ulagellam Technologies Pvt Ltd. All Rights Reserved."

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "B104 Greenwoods, Morais City, Trichy, Tamil Nadu, India 620007"
phone = ["+91-86676-88027"]
email = ["uma@ulagellam.com"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon2.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Buy Premium"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = false
title = "Get Andromeda-Premium Now"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Download The Theme"
button_link = "https://gethugothemes.com/products/andromeda/"

############################# social site ########################
[[social]]
title = "Ulagellam Facebook"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://facebook.com/ulagellam"

[[social]]
title = "Ulagellam Twitter"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "https://twitter.com/umamaheswarantg"

[[social]]
title = "Ulagellam Linkedin"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://linkedin.com/in/umamaheswarantg"

[[social]]
title = "Ulagellam Youtube"
icon = "lab la-youtube" # https://icons8.com/line-awesome
link = "https://www.youtube.com/channel/UClind4orH7yfe0Qp9bzm6ug"
